# Generated by Django 4.2 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
