# Generated by Django 4.2 on 2026-07-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_patient_insurance_company'),
        ('claims', '0002_claim_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='accounts.insurancecompany'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.insuranceprovider'),
        ),
        migrations.AlterField(
            model_name='document',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.insuranceprovider'),
        ),
    ]
