# Generated by Django 4.2 on 2026-06-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('PROVIDER', 'Healthcare Provider'), ('ADMIN', 'Administrator')], default='PATIENT', max_length=20),
        ),
    ]
