# Generated by Django 4.2 on 2026-06-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_insurancecompany_patient_corporate_scheme_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id_document_upload',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_card_upload',
        ),
    ]
