# Generated by Django 4.2 on 2026-07-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role_insuranceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprovider',
            name='bed_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='date_established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='facility_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='facility_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('', 'Select facility type'), ('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('DIAGNOSTIC_LAB', 'Diagnostic Laboratory'), ('PHARMACY', 'Pharmacy'), ('DENTAL', 'Dental Clinic'), ('MATERNITY', 'Maternity Home')], max_length=30),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='moh_registration_number',
            field=models.CharField(blank=True, help_text='Ministry of Health / KMPDC facility registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='physical_address',
            field=models.TextField(blank=True),
        ),
    ]
