# Generated by Django 4.2 on 2026-07-03 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_healthcareprovider_bed_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceprovider',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.insurancecompany'),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='job_title',
            field=models.CharField(blank=True, choices=[('', 'Select job title'), ('CLAIMS_OFFICER', 'Claims Officer'), ('CLAIMS_MANAGER', 'Claims Manager'), ('DOCUMENT_VERIFICATION_OFFICER', 'Document Verification Officer'), ('UNDERWRITER', 'Underwriter'), ('CUSTOMER_SERVICE_OFFICER', 'Customer Service Officer'), ('BRANCH_MANAGER', 'Branch Manager')], max_length=40),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='office_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='work_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
