# Generated by Django 4.2 on 2026-07-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_insuranceprovider_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='accounts.insurancecompany'),
        ),
    ]
