# Generated by Django 4.2 on 2026-06-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-generated_at']},
        ),
    ]
