# Generated by Django 4.2 on 2026-07-03 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role_insuranceprovider'),
        ('notifications', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.insuranceprovider'),
        ),
    ]
